# Generated by Django 5.1.2 on 2024-10-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMetric',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
