version: '3'

services:
  redis:
    image: redis:6.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
  
  web:
    build:
      context: .
    container_name: django_server
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build:
      context: .
    container_name: celery_worker
    command: celery -A djangotemplate worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  flower:
    build:
      context: .
    container_name: celery_flower
    ports:
      - "5555:5555"
    command: celery -A djangotemplate flower --port=5555
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
volumes:
  redis-data:
