services:
  redis:
    image: redis:6.0-alpine
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
    container_name: django_server
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A djangotemplate worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat: # celery scheduller tasks
    build:
      context: .
    container_name: celery_beat
    command: celery -A djangotemplate beat --loglevel=DEBUG --schedule=/app/celerybeat-schedule
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-flower:
    build:
      context: .
    container_name: celery_flower
    ports:
      - "5555:5555"
    command: celery -A djangotemplate flower --port=5555
    volumes:
      - .:/app
    depends_on:
      - celery-worker
      - redis
      - celery-beat
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    volumes:
      - ${HOME}/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  redis-data:
