# Generated by Django 5.1.2 on 2024-10-21 14:17

import outbox.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id not sequential using UUID Field', primary_key=True, serialize=False, unique=True)),
                ('msg_id', models.CharField(max_length=100, null=True)),
                ('headers', models.JSONField(null=True)),
                ('body', models.JSONField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(default=outbox.models._one_more_day)),
                ('retry', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(-1, 'Failed'), (1, 'Schedule'), (2, 'Succeeded')], default=2)),
            ],
            options={
                'verbose_name': 'custom_received',
                'db_table': 'custom_received',
            },
        ),
    ]
